FROM debian
MAINTAINER Wilton Guilherme - TBF HOST <wiltoninfra@gmail.com>
RUN apt-get update
RUN apt-get install software-properties-common -y
RUN apt update && apt install -y \
	curl 		\
	dnsutils 	\
	gcc			\
	wget 		\
	build-essential 	\
	git 	\
	g++ 	\
	vim		\
	cron	\
	openssh-server \
	make \
	mongodb

EXPOSE 27017
CMD ["mongod"]
CMD sleep 86400
