FROM debian

MAINTAINER Wilton Guilherme - TBF HOST <wiltoninfra@gmail.com>



RUN apt-get update

RUN apt-get install software-properties-common -y


RUN apt update && apt install -y \
	curl 		\
	dnsutils 	\
	gcc			\
	wget 		\
	build-essential 	\
	git 	\
	g++ 	\
	vim		\
	cron	\
	openssh-server \
	make \
	memcached


EXPOSE 11211
CMD ["memcached"]
CMD sleep 86400